#!/usr/bin/env python3
"""
flag_analysis.py

Analyses the eight fraud-indicator flags and LLM risk scores in
EMSCAD_fraud_detection.csv and exports three result tables.

Sections
────────────────────────────────────────────────────────────────────────
  1. Flag prevalence and fraud relevance
     For each of the 8 binary flag columns:
       • how many postings carry the flag (prevalence)
       • fraud rate without vs. with the flag
       • difference in fraud rate (percentage-points)
       • relative risk  (fraud_with / fraud_without)
       • chi-square or Fisher's exact test  (auto-selected on expected freq)
       • significance stars  (*** p<0.001  ** p<0.01  * p<0.05)

  2. Flag co-occurrence and fraud rate
     For each level of total flags fired (0 … 8):
       • number of postings at that level
       • percentage of the full dataset
       • number of fraudulent postings
       • fraud rate (%)
     Plus a Spearman correlation: total_flags → fraudulent

  3. Risk score distribution by fraud status
     For each of the four risk score columns generated by fraud_detector.py
     and single_pass_detector.py:
       • mean / median / std / min / max  for legit vs. fraud postings
       • Mann-Whitney U test  (non-parametric; risk scores are ordinal 0-10)
       • AUROC  (how well the score separates fraud from legit)

Outputs (saved to results/)
────────────────────────────────────────────────────────────────────────
  flag_prevalence_analysis.csv
  flag_agreement_analysis.csv
  risk_score_distribution.csv

Usage
────────────────────────────────────────────────────────────────────────
  python flag_analysis.py
"""

import sys
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.stats import chi2_contingency, fisher_exact, mannwhitneyu, spearmanr
from sklearn.metrics import roc_auc_score

# ── Paths ──────────────────────────────────────────────────────────────────────
_HERE       = Path(__file__).resolve().parent
DATA_PATH   = _HERE / "EMSCAD_fraud_detection.csv"
RESULTS_DIR = _HERE / "results"

# ── Column definitions ─────────────────────────────────────────────────────────
FLAG_COLS = {
    'flag1_sensitive_info':   'Sensitive Information Request',
    'flag2_unrealistic_comp': 'Unrealistic Compensation',
    'flag3_pressure_tactics': 'Pressure Tactics',
    'flag4_anon_employer':    'Unidentifiable Employer',
    'flag5_req_role_mismatch':'Requirements Role Mismatch',
    'flag6_info_conflict':    'Internal Information Conflict',
    'flag7_vague_info':       'Vague Information',
    'flag8_promo_template':   'Promotional Template Substitution',
}

SCORE_COLS = {
    'risk_score_all':             'Multi-Agent (all 3)',
    'risk_score_legit_context':   'Multi-Agent (legit + context)',
    'risk_score_context_consist': 'Multi-Agent (context + consist)',
    'risk_score_legit_consist':   'Multi-Agent (legit + consist)',
    'single_pass_risk_score':     'Single-Pass GPT-4o',
}

TARGET = 'fraudulent_agent'


# ══════════════════════════════════════════════════════════════════════════════
# Data loading
# ══════════════════════════════════════════════════════════════════════════════

def load_data() -> pd.DataFrame:
    df = pd.read_csv(DATA_PATH, encoding='latin-1', low_memory=False)

    # Accept either column name for the fraud label
    if TARGET not in df.columns and 'fraudulent' in df.columns:
        df = df.rename(columns={'fraudulent': TARGET})
    if TARGET not in df.columns:
        sys.exit(f"Target column '{TARGET}' not found in {DATA_PATH.name}.")

    # Coerce flag columns to int (they may be stored as float after CSV round-trip)
    for col in FLAG_COLS:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors='coerce').fillna(0).astype(int)

    return df


# ══════════════════════════════════════════════════════════════════════════════
# Section 1 — Flag prevalence and fraud relevance
# ══════════════════════════════════════════════════════════════════════════════

def _sig_stars(p: float) -> str:
    if p < 0.001: return '***'
    if p < 0.01:  return '**'
    if p < 0.05:  return '*'
    return 'ns'


def flag_prevalence_analysis(df: pd.DataFrame) -> pd.DataFrame:
    """
    For each flag column, compute prevalence, fraud rates, relative risk,
    and a chi-square or Fisher's exact test.
    Auto-selects Fisher's exact when any expected cell frequency < 5.
    """
    rows = []
    n_total  = len(df)
    n_fraud  = int(df[TARGET].sum())
    base_rate = n_fraud / n_total * 100

    for col, label in FLAG_COLS.items():
        if col not in df.columns:
            continue

        flagged     = df[col] == 1
        n_flagged   = int(flagged.sum())
        n_unflagged = n_total - n_flagged

        if n_flagged == 0:
            continue

        fraud_with    = df[flagged][TARGET].mean() * 100
        fraud_without = df[~flagged][TARGET].mean() * 100

        diff_pp = fraud_with - fraud_without
        rel_risk = fraud_with / fraud_without if fraud_without > 0 else np.inf

        # Contingency table: rows = flag (0/1), cols = fraud (0/1)
        ct = pd.crosstab(df[col], df[TARGET])
        _, _, _, expected = chi2_contingency(ct)

        if expected.min() < 5:
            odds, p_val = fisher_exact(ct)
            test_used = 'Fisher'
        else:
            chi2, p_val, _, _ = chi2_contingency(ct)
            test_used = 'Chi-sq'

        rows.append({
            'Flag':                   label,
            'Column':                 col,
            'Flagged (n)':            n_flagged,
            'Prevalence (%)':         round(n_flagged / n_total * 100, 2),
            'Base Fraud Rate (%)':    round(base_rate,    2),
            'Fraud Rate Without (%)': round(fraud_without, 2),
            'Fraud Rate With (%)':    round(fraud_with,    2),
            'Difference (pp)':        round(diff_pp,       2),
            'Relative Risk':          round(rel_risk,       2),
            'p-value':                round(float(p_val),   4),
            'Sig':                    _sig_stars(float(p_val)),
            'Test':                   test_used,
        })

    df_out = pd.DataFrame(rows).sort_values('Relative Risk', ascending=False)
    return df_out


# ══════════════════════════════════════════════════════════════════════════════
# Section 2 — Flag co-occurrence and fraud rate
# ══════════════════════════════════════════════════════════════════════════════

def flag_agreement_analysis(df: pd.DataFrame) -> tuple:
    """
    Compute fraud rate by total number of flags fired (0 … 8).
    Returns (agreement_df, spearman_rho, spearman_p).
    """
    available = [c for c in FLAG_COLS if c in df.columns]
    df = df.copy()
    df['total_flags'] = df[available].sum(axis=1)

    agg = (
        df.groupby('total_flags')[TARGET]
        .agg(total_postings='count', fraudulent_postings='sum')
        .reset_index()
    )
    agg['Percentage of Postings (%)'] = (
        agg['total_postings'] / len(df) * 100
    ).round(2)
    agg['Fraud Rate (%)'] = (
        agg['fraudulent_postings'] / agg['total_postings'] * 100
    ).round(2)

    agg = agg.rename(columns={
        'total_flags':          'Number of Flags Fired',
        'total_postings':       'Total Postings',
        'fraudulent_postings':  'Fraudulent Postings',
    })[['Number of Flags Fired', 'Total Postings',
        'Percentage of Postings (%)', 'Fraudulent Postings',
        'Fraud Rate (%)']]

    rho, p_val = spearmanr(df['total_flags'], df[TARGET])
    return agg, float(rho), float(p_val)


# ══════════════════════════════════════════════════════════════════════════════
# Section 3 — Risk score distribution by fraud status
# ══════════════════════════════════════════════════════════════════════════════

def risk_score_distribution(df: pd.DataFrame) -> pd.DataFrame:
    """
    For each available risk score column, compute descriptive stats
    for legit vs. fraud postings, Mann-Whitney U test, and AUROC.
    """
    rows = []
    fraud_mask = df[TARGET] == 1
    legit_mask = df[TARGET] == 0

    for col, label in SCORE_COLS.items():
        if col not in df.columns:
            continue
        series = pd.to_numeric(df[col], errors='coerce')
        valid  = series.notna()
        if valid.sum() == 0:
            continue

        s_fraud = series[valid & fraud_mask].dropna()
        s_legit = series[valid & legit_mask].dropna()

        if len(s_fraud) == 0 or len(s_legit) == 0:
            continue

        # Mann-Whitney U
        stat, p_mw = mannwhitneyu(s_fraud, s_legit, alternative='greater')

        # AUROC
        y_true = df[TARGET][valid].values
        y_score = series[valid].values
        try:
            auroc = roc_auc_score(y_true, y_score)
        except Exception:
            auroc = np.nan

        rows.append({
            'Score':              label,
            'Column':             col,
            'N (total)':          int(valid.sum()),
            'N (legit)':          len(s_legit),
            'N (fraud)':          len(s_fraud),
            'Mean (legit)':       round(s_legit.mean(),  3),
            'Mean (fraud)':       round(s_fraud.mean(),  3),
            'Median (legit)':     round(s_legit.median(), 1),
            'Median (fraud)':     round(s_fraud.median(), 1),
            'Std (legit)':        round(s_legit.std(),   3),
            'Std (fraud)':        round(s_fraud.std(),   3),
            'Mann-Whitney p':     round(float(p_mw),     4),
            'Sig':                _sig_stars(float(p_mw)),
            'AUROC':              round(float(auroc),    4),
        })

    return pd.DataFrame(rows)


# ══════════════════════════════════════════════════════════════════════════════
# Printing helpers
# ══════════════════════════════════════════════════════════════════════════════

def _print_section(title: str) -> None:
    print()
    print("=" * 72)
    print(f"  {title}")
    print("=" * 72)


def _print_df(df: pd.DataFrame, float_fmt: str = '{:.4f}') -> None:
    with pd.option_context(
        'display.width', 130,
        'display.float_format', float_fmt.format,
        'display.max_rows', 50,
    ):
        print(df.to_string(index=False))


# ══════════════════════════════════════════════════════════════════════════════
# Main
# ══════════════════════════════════════════════════════════════════════════════

def main() -> None:
    print("=" * 72)
    print("  EMSCAD Fraud Detection — Flag & Risk Score Analysis")
    print("=" * 72)

    if not DATA_PATH.exists():
        sys.exit(f"\nData file not found:\n  {DATA_PATH}\n")

    # ── Load ──────────────────────────────────────────────────────────────
    print(f"\nLoading {DATA_PATH.name} …")
    df = load_data()
    n_total = len(df)
    n_fraud = int(df[TARGET].sum())
    print(f"  {n_total:,} postings  |  "
          f"{n_fraud:,} fraudulent ({n_fraud/n_total*100:.2f}%)")

    available_flags  = [c for c in FLAG_COLS  if c in df.columns]
    available_scores = [c for c in SCORE_COLS if c in df.columns]
    print(f"  Flag columns found    : {len(available_flags)}/8")
    print(f"  Score columns found   : {len(available_scores)}/{len(SCORE_COLS)}")

    if not available_flags:
        print("\n  WARNING: no flag columns found.")
        print("  Run fraud_detector.py first to generate flag columns.")

    RESULTS_DIR.mkdir(exist_ok=True)

    # ── Section 1: Flag prevalence ────────────────────────────────────────
    _print_section("SECTION 1 — FLAG PREVALENCE AND FRAUD RELEVANCE")
    df_prev = flag_prevalence_analysis(df)
    _print_df(df_prev)

    out1 = RESULTS_DIR / 'flag_prevalence_analysis.csv'
    df_prev.to_csv(out1, index=False)
    print(f"\n  Saved → {out1.name}  {df_prev.shape}")

    # ── Section 2: Flag co-occurrence ─────────────────────────────────────
    _print_section("SECTION 2 — FLAG CO-OCCURRENCE AND FRAUD RATE")
    df_agree, rho, p_rho = flag_agreement_analysis(df)
    _print_df(df_agree, '{:.2f}')

    sig = _sig_stars(p_rho)
    print(f"\n  Spearman correlation (total flags → fraud):  "
          f"ρ = {rho:.3f}   p = {p_rho:.4f}  {sig}")
    if rho > 0 and p_rho < 0.05:
        print("  → More flags fired = higher fraud probability.")

    # Append Spearman result as a footer row to the saved CSV
    footer = pd.DataFrame([{
        'Number of Flags Fired': 'Spearman ρ',
        'Total Postings': '',
        'Percentage of Postings (%)': '',
        'Fraudulent Postings': round(rho, 4),
        'Fraud Rate (%)': round(p_rho, 4),
    }])
    df_agree_save = pd.concat([df_agree, footer], ignore_index=True)
    out2 = RESULTS_DIR / 'flag_agreement_analysis.csv'
    df_agree_save.to_csv(out2, index=False)
    print(f"\n  Saved → {out2.name}  {df_agree.shape}")

    # ── Section 3: Risk score distribution ───────────────────────────────
    _print_section("SECTION 3 — RISK SCORE DISTRIBUTION (fraud vs. legit)")
    if not available_scores:
        print("  No risk score columns found.")
        print("  Run fraud_detector.py and single_pass_detector.py first.")
    else:
        df_scores = risk_score_distribution(df)
        _print_df(df_scores, '{:.3f}')

        out3 = RESULTS_DIR / 'risk_score_distribution.csv'
        df_scores.to_csv(out3, index=False)
        print(f"\n  Saved → {out3.name}  {df_scores.shape}")

    # ── Final summary ─────────────────────────────────────────────────────
    print()
    print("=" * 72)
    print("  Outputs saved to results/")
    print("    flag_prevalence_analysis.csv")
    print("    flag_agreement_analysis.csv")
    if available_scores:
        print("    risk_score_distribution.csv")
    print("=" * 72)


if __name__ == "__main__":
    main()
